# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET package automated build, test and push to NuGet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=<Version>).*(?=</Version>)' TemperatureConverter/TemperatureConverter.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Increment version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          IFS='.' read -ra ADDR <<< "$VERSION"
          ADDR[2]=$((ADDR[2] + 1))
          NEW_VERSION="${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" TemperatureConverter/TemperatureConverter.csproj
          sed -i "s|<AssemblyVersion>.*</AssemblyVersion>|<AssemblyVersion>$NEW_VERSION.0</AssemblyVersion>|" TemperatureConverter/TemperatureConverter.csproj
          sed -i "s|<FileVersion>.*</FileVersion>|<FileVersion>$NEW_VERSION.0</FileVersion>|" TemperatureConverter/TemperatureConverter.csproj
          sed -i "s|<InformationalVersion>.*</InformationalVersion>|<InformationalVersion>$NEW_VERSION.0</InformationalVersion>|" TemperatureConverter/TemperatureConverter.csproj

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack
        run: dotnet pack TemperatureConverter/TemperatureConverter.csproj --output nuget-packages --configuration Release

      - name: Publish
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

      - name: Commit version increment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TemperatureConverter/TemperatureConverter.csproj
          git commit -m "Increment version [skip ci]"
          git push