name: Build, Test, and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
    
    - name: Get commit count
      id: commit-count
      run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
    
    - name: Pack
      run: dotnet pack src/TemperatureConverter/TemperatureConverter.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.date.outputs.date }}.${{ steps.commit-count.outputs.count }}
    
    - name: Publish
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
